name: Wireguard
description: Apply wireguard config
version: 1.0.3
slug: wireguard
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_network: true
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
options:
  Stay_up: true
schema:
  Stay_up: bool
